apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-expressjs-8au7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-expressjs-8au7
    app.kubernetes.io/part-of: sample-expressjs
  name: sample-expressjs-8au7
  namespace: bbrownin-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sample-expressjs-8au7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sample-expressjs-8au7
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:a2d4de2e45b18923976c36653131d2e7590a7be55bfb32084cc1a2829d49bdc9
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
