apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-expressjs-8au7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-expressjs-8au7
    app.kubernetes.io/part-of: sample-expressjs
  name: sample-expressjs-8au7
  namespace: bbrownin-tenant
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sample-expressjs-8au7
    weight: 100
status: {}
