apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-expressjs-8au7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-expressjs-8au7
    app.kubernetes.io/part-of: sample-expressjs
  name: sample-expressjs-8au7
  namespace: bbrownin-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: sample-expressjs-8au7
status:
  loadBalancer: {}
